//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/_Scripts/Player/HGPlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/_Scripts/Player/HGPlayerControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @HGPlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @HGPlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""HGPlayerControls"",
    ""maps"": [
        {
            ""name"": ""InGameActionMap"",
            ""id"": ""7fa6ccb1-af9f-42c3-9a6c-31ce47e2a4d0"",
            ""actions"": [
                {
                    ""name"": ""MoveAction"",
                    ""type"": ""Value"",
                    ""id"": ""00a30f46-b898-44ac-86b1-92e0f98ad325"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseAction"",
                    ""type"": ""Button"",
                    ""id"": ""ad30cb5b-4a6f-46d1-8014-0de87d85f777"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AggressiveAction"",
                    ""type"": ""Button"",
                    ""id"": ""b31d2ea8-998a-4622-9a69-425d3868b558"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LookAction"",
                    ""type"": ""Value"",
                    ""id"": ""0bb0d7ad-b270-464e-9c06-f930cf5a2d50"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectInventory01"",
                    ""type"": ""Button"",
                    ""id"": ""5043d26a-5ff5-44cf-9ebe-72b7c97ad41f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectInventory02"",
                    ""type"": ""Button"",
                    ""id"": ""2a2e616f-a483-46e7-b1d3-ea3b7ec45a32"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextInventory"",
                    ""type"": ""Button"",
                    ""id"": ""f3c8f6e1-4701-41e6-9372-cb11f42860d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleRun"",
                    ""type"": ""Button"",
                    ""id"": ""f226bc3d-465d-418d-a2c7-a4d976c7b665"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2ba2f08b-b2eb-4652-9822-b29abd9819f0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAction"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bdf27976-f161-4190-8e34-918e4432621b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ef0a52c1-931b-4310-95b5-26ced41c49f5"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2166c400-d6c1-4c76-8345-9ba1c49a9155"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""84899c93-4f79-4f21-99bf-eb2f289c1954"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4e387ca0-f2f4-4fd8-b53e-97c072cef38b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f0ef6f43-f3f0-4a76-b9b4-d2ec78470ad9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""726462ee-d6d5-44e7-97c2-4a43e93bf156"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""127c3630-ad37-4711-b94f-4a440af58fd4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""MoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""903a8d76-0243-4911-a7b5-d30a0f59799c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""UseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c53817e-0ac9-432e-b101-171bb54253c6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KBM"",
                    ""action"": ""AggressiveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""327a469c-8c27-41e0-a808-733042bc88b2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa8b6345-bb5c-4007-be17-c0941a559d80"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectInventory01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77d23e61-8571-4d31-87f6-1cff39157336"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectInventory02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bb71b5f-ada6-4236-b9e7-bfbfa982e0cb"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f13399d7-d585-48b9-8afb-179b0268d2b5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KBM"",
            ""bindingGroup"": ""KBM"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // InGameActionMap
        m_InGameActionMap = asset.FindActionMap("InGameActionMap", throwIfNotFound: true);
        m_InGameActionMap_MoveAction = m_InGameActionMap.FindAction("MoveAction", throwIfNotFound: true);
        m_InGameActionMap_UseAction = m_InGameActionMap.FindAction("UseAction", throwIfNotFound: true);
        m_InGameActionMap_AggressiveAction = m_InGameActionMap.FindAction("AggressiveAction", throwIfNotFound: true);
        m_InGameActionMap_LookAction = m_InGameActionMap.FindAction("LookAction", throwIfNotFound: true);
        m_InGameActionMap_SelectInventory01 = m_InGameActionMap.FindAction("SelectInventory01", throwIfNotFound: true);
        m_InGameActionMap_SelectInventory02 = m_InGameActionMap.FindAction("SelectInventory02", throwIfNotFound: true);
        m_InGameActionMap_NextInventory = m_InGameActionMap.FindAction("NextInventory", throwIfNotFound: true);
        m_InGameActionMap_ToggleRun = m_InGameActionMap.FindAction("ToggleRun", throwIfNotFound: true);
    }

    ~@HGPlayerControls()
    {
        UnityEngine.Debug.Assert(!m_InGameActionMap.enabled, "This will cause a leak and performance issues, HGPlayerControls.InGameActionMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGameActionMap
    private readonly InputActionMap m_InGameActionMap;
    private List<IInGameActionMapActions> m_InGameActionMapActionsCallbackInterfaces = new List<IInGameActionMapActions>();
    private readonly InputAction m_InGameActionMap_MoveAction;
    private readonly InputAction m_InGameActionMap_UseAction;
    private readonly InputAction m_InGameActionMap_AggressiveAction;
    private readonly InputAction m_InGameActionMap_LookAction;
    private readonly InputAction m_InGameActionMap_SelectInventory01;
    private readonly InputAction m_InGameActionMap_SelectInventory02;
    private readonly InputAction m_InGameActionMap_NextInventory;
    private readonly InputAction m_InGameActionMap_ToggleRun;
    /// <summary>
    /// Provides access to input actions defined in input action map "InGameActionMap".
    /// </summary>
    public struct InGameActionMapActions
    {
        private @HGPlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public InGameActionMapActions(@HGPlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/MoveAction".
        /// </summary>
        public InputAction @MoveAction => m_Wrapper.m_InGameActionMap_MoveAction;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/UseAction".
        /// </summary>
        public InputAction @UseAction => m_Wrapper.m_InGameActionMap_UseAction;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/AggressiveAction".
        /// </summary>
        public InputAction @AggressiveAction => m_Wrapper.m_InGameActionMap_AggressiveAction;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/LookAction".
        /// </summary>
        public InputAction @LookAction => m_Wrapper.m_InGameActionMap_LookAction;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/SelectInventory01".
        /// </summary>
        public InputAction @SelectInventory01 => m_Wrapper.m_InGameActionMap_SelectInventory01;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/SelectInventory02".
        /// </summary>
        public InputAction @SelectInventory02 => m_Wrapper.m_InGameActionMap_SelectInventory02;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/NextInventory".
        /// </summary>
        public InputAction @NextInventory => m_Wrapper.m_InGameActionMap_NextInventory;
        /// <summary>
        /// Provides access to the underlying input action "InGameActionMap/ToggleRun".
        /// </summary>
        public InputAction @ToggleRun => m_Wrapper.m_InGameActionMap_ToggleRun;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_InGameActionMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="InGameActionMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(InGameActionMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="InGameActionMapActions" />
        public void AddCallbacks(IInGameActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionMapActionsCallbackInterfaces.Add(instance);
            @MoveAction.started += instance.OnMoveAction;
            @MoveAction.performed += instance.OnMoveAction;
            @MoveAction.canceled += instance.OnMoveAction;
            @UseAction.started += instance.OnUseAction;
            @UseAction.performed += instance.OnUseAction;
            @UseAction.canceled += instance.OnUseAction;
            @AggressiveAction.started += instance.OnAggressiveAction;
            @AggressiveAction.performed += instance.OnAggressiveAction;
            @AggressiveAction.canceled += instance.OnAggressiveAction;
            @LookAction.started += instance.OnLookAction;
            @LookAction.performed += instance.OnLookAction;
            @LookAction.canceled += instance.OnLookAction;
            @SelectInventory01.started += instance.OnSelectInventory01;
            @SelectInventory01.performed += instance.OnSelectInventory01;
            @SelectInventory01.canceled += instance.OnSelectInventory01;
            @SelectInventory02.started += instance.OnSelectInventory02;
            @SelectInventory02.performed += instance.OnSelectInventory02;
            @SelectInventory02.canceled += instance.OnSelectInventory02;
            @NextInventory.started += instance.OnNextInventory;
            @NextInventory.performed += instance.OnNextInventory;
            @NextInventory.canceled += instance.OnNextInventory;
            @ToggleRun.started += instance.OnToggleRun;
            @ToggleRun.performed += instance.OnToggleRun;
            @ToggleRun.canceled += instance.OnToggleRun;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="InGameActionMapActions" />
        private void UnregisterCallbacks(IInGameActionMapActions instance)
        {
            @MoveAction.started -= instance.OnMoveAction;
            @MoveAction.performed -= instance.OnMoveAction;
            @MoveAction.canceled -= instance.OnMoveAction;
            @UseAction.started -= instance.OnUseAction;
            @UseAction.performed -= instance.OnUseAction;
            @UseAction.canceled -= instance.OnUseAction;
            @AggressiveAction.started -= instance.OnAggressiveAction;
            @AggressiveAction.performed -= instance.OnAggressiveAction;
            @AggressiveAction.canceled -= instance.OnAggressiveAction;
            @LookAction.started -= instance.OnLookAction;
            @LookAction.performed -= instance.OnLookAction;
            @LookAction.canceled -= instance.OnLookAction;
            @SelectInventory01.started -= instance.OnSelectInventory01;
            @SelectInventory01.performed -= instance.OnSelectInventory01;
            @SelectInventory01.canceled -= instance.OnSelectInventory01;
            @SelectInventory02.started -= instance.OnSelectInventory02;
            @SelectInventory02.performed -= instance.OnSelectInventory02;
            @SelectInventory02.canceled -= instance.OnSelectInventory02;
            @NextInventory.started -= instance.OnNextInventory;
            @NextInventory.performed -= instance.OnNextInventory;
            @NextInventory.canceled -= instance.OnNextInventory;
            @ToggleRun.started -= instance.OnToggleRun;
            @ToggleRun.performed -= instance.OnToggleRun;
            @ToggleRun.canceled -= instance.OnToggleRun;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InGameActionMapActions.UnregisterCallbacks(IInGameActionMapActions)" />.
        /// </summary>
        /// <seealso cref="InGameActionMapActions.UnregisterCallbacks(IInGameActionMapActions)" />
        public void RemoveCallbacks(IInGameActionMapActions instance)
        {
            if (m_Wrapper.m_InGameActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="InGameActionMapActions.AddCallbacks(IInGameActionMapActions)" />
        /// <seealso cref="InGameActionMapActions.RemoveCallbacks(IInGameActionMapActions)" />
        /// <seealso cref="InGameActionMapActions.UnregisterCallbacks(IInGameActionMapActions)" />
        public void SetCallbacks(IInGameActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="InGameActionMapActions" /> instance referencing this action map.
    /// </summary>
    public InGameActionMapActions @InGameActionMap => new InGameActionMapActions(this);
    private int m_KBMSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KBM");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "InGameActionMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="InGameActionMapActions.AddCallbacks(IInGameActionMapActions)" />
    /// <seealso cref="InGameActionMapActions.RemoveCallbacks(IInGameActionMapActions)" />
    public interface IInGameActionMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AggressiveAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAggressiveAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LookAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLookAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectInventory01" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectInventory01(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectInventory02" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectInventory02(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextInventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleRun" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleRun(InputAction.CallbackContext context);
    }
}
